/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;

const CACHE_NAME = `bandchamp-${version}`;
const IMAGE_CACHE_NAME = 'bandchamp-images';
const AUDIO_CACHE_NAME = 'bandchamp-audio';

// Assets generated by the build process + static files
const ASSETS = [...build, ...files];

sw.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => sw.skipWaiting()),
  );
});

sw.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then(async (keys) => {
      for (const key of keys) {
        if (key !== CACHE_NAME && key !== IMAGE_CACHE_NAME && key !== AUDIO_CACHE_NAME) {
          await caches.delete(key);
        }
      }
      await sw.clients.claim();
    }),
  );
});

sw.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // Skip non-GET requests
  if (event.request.method !== 'GET') return;

  // Skip API proxy requests (always network)
  if (url.pathname.startsWith('/api/')) return;

  // Skip chrome-extension and other non-http schemes
  if (!url.protocol.startsWith('http')) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE_NAME);

      // For app shell assets: cache-first
      if (ASSETS.includes(url.pathname)) {
        const cached = await cache.match(event.request);
        if (cached) return cached;
      }

      // For Bandcamp assets (cover art + audio streams): persistent cache-first
      if (url.hostname.includes('bcbits.com') || url.hostname.includes('bandcamp.com')) {
        // Check audio cache first (for pre-cached streams)
        const audioCache = await caches.open(AUDIO_CACHE_NAME);
        const audioCached = await audioCache.match(event.request);
        if (audioCached) return audioCached;

        // Then check image cache
        const imageCache = await caches.open(IMAGE_CACHE_NAME);
        const cached = await imageCache.match(event.request);
        if (cached) return cached;

        try {
          const response = await fetch(event.request);
          if (response.ok && response.status === 200) {
            imageCache.put(event.request, response.clone());
          }
          return response;
        } catch {
          // Return a placeholder if offline
          return new Response('', { status: 408, statusText: 'Offline' });
        }
      }

      // For navigation requests: network-first, fallback to cached shell
      if (event.request.mode === 'navigate') {
        try {
          const response = await fetch(event.request);
          cache.put(event.request, response.clone());
          return response;
        } catch {
          const cached = await cache.match(event.request);
          if (cached) return cached;

          // Fallback to root page
          const root = await cache.match('/');
          if (root) return root;

          return new Response('Offline', { status: 503 });
        }
      }

      // Everything else: network-first
      try {
        const response = await fetch(event.request);
        if (response.ok) {
          cache.put(event.request, response.clone());
        }
        return response;
      } catch {
        const cached = await cache.match(event.request);
        return cached || new Response('Offline', { status: 503 });
      }
    })(),
  );
});
